import sys
sys.path.append("../Controls/Mididings/")

from ports import *

def climat_granmounoute(seq.timer):
  seq.send('/pyta/text', 2, 'Gran Mounoute  ')
  seq.send('/pyta/text/visible', 2, 1)
  timer.wait(1, 's')
  seq.send(rpicourport, '/pyta/text', 2, 'Grand Moumouté ?')
  timer.wait(1.2, 's')
  seq.send(rpicourport, '/pyta/text', 2, 'Wisdom...')
  timer.wait(0.4, 's')
  seq.send(rpicourport, '/pyta/text', 2, 'Grand Mère sait faire un bon café ?')
  timer.wait(2, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Kondom...')
  timer.wait(1, 's')
  seq.send('/pyta/text/visible', 2, 0)  

def climat_dignite(seq.timer):
  seq.send('/pyta/text', 2, 'Dignité  ')
  seq.send('/pyta/text/visible', 2, 1)
  timer.wait(0.5, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Dingité')
  timer.wait(1.2, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Dingle Dongle Dungle')
  seq.send(rpicourport, '/pyta/text', 2, 'Ignifugé')
  timer.wait(0.4, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Dingle Dongle Dungle')
  timer.wait(0.1, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Infirmité')
  timer.wait(0.1, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Dingle Dongle Dungle')
  timer.wait(0.1, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'InFRIMEité')
  timer.wait(2, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Dingle Dongle Dungle')
  seq.send(rpicourport, '/pyta/text', 2, 'Soirée Infirmières')
  timer.wait(1, 's')
  seq.send('/pyta/text/visible', 2, 0)


def climat_eternite(seq.timer):
  seq.send('/pyta/text', 2, 'Eternité')
  seq.send('/pyta/text/visible', 2, 1)
  timer.wait(0.5, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Etrenité')
  timer.wait(1.2, 's')
  seq.send(rpicourport, '/pyta/text', 2, 'Enucléé')
  timer.wait(0.4, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'NUclear Weap')
  timer.wait(0.1, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Z')
  timer.wait(0.1, 's')
  seq.send(rpicourport, '/pyta/text', 2, 'zzzzzzzzzzzzz')
  timer.wait(0.1, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'ZnuKzz')
  timer.wait(2, 's')
  seq.send(rpijardinport, '/pyta/text', 2, 'Z')
  seq.send(rpicourport, '/pyta/text', 2, 'Z')
  timer.wait(1, 's')
  seq.send('/pyta/text/visible', 2, 0)  
