import sys
sys.path.append("../Controls/Mididings/")

from ports import *

def dafist_intro(seq, timer):
    seq.send('/CC/White/Segment/All', 255)
    seq.send('/CJ/White/Segment/All', 255)

    seq.send(vporlport,'/pyta/slide/rotate_z', 63, -90)
    seq.send(vporlport,'/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vporlport,'/pyta/slide/visible', 63, 1)

    seq.send(vpjeannotport,'/pyta/slide/rotate_z', 63, 90)
    seq.send(vpjeannotport,'/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vpjeannotport,'/pyta/slide/visible', 63, 1)

def dafist_entreeinstru(seq, timer):
    seq.send('/CC/White/Segment/1', 100)
    seq.send('/CC/White/Segment/2', 75)
    seq.send('/CC/White/Segment/3', 50)
    seq.send('/CC/White/Segment/4', 25)
    seq.send('/CJ/White/Segment/8', 100)
    seq.send('/CJ/White/Segment/7', 75)
    seq.send('/CJ/White/Segment/6', 50)
    seq.send('/CJ/White/Segment/5', 25)

    seq.send(vporlport,'/pyta/slide/rotate_z', 63, -90)
    seq.send(vporlport,'/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vporlport,'/pyta/slide/visible', 63, 1)

    seq.send(vpjeannotport,'/pyta/slide/rotate_z', 63, 90)
    seq.send(vpjeannotport,'/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vpjeannotport,'/pyta/slide/visible', 63, 1)

def dafist_leslie_j(seq, timer):
    seq.animate([vpjeannotport, '/pyta/slide/scale_y', 63], 768, 0, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.send(vpjeannotport, '/pyta/slide/rotate_z', 63, -90)
    seq.animate([vpjeannotport, '/pyta/slide/scale_y', 63], 0, 768, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.animate([vpjeannotport, '/pyta/slide/scale_y', 63], 768, 0, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.send(vpjeannotport, '/pyta/slide/rotate_z', 63, 90)
    seq.animate([vpjeannotport, '/pyta/slide/scale_y', 63], 0, 768, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')

def dafist_leslie_o(seq, timer):
    seq.animate([vporlport, '/pyta/slide/scale_y', 63], 768, 0, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.send(vporlport, '/pyta/slide/rotate_z', 63, -90)
    seq.animate([vporlport, '/pyta/slide/scale_y', 63], 0, 768, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.animate([vporlport, '/pyta/slide/scale_y', 63], 768, 0, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')
    seq.send(vporlport, '/pyta/slide/rotate_z', 63, 90)
    seq.animate([vporlport, '/pyta/slide/scale_y', 63], 0, 768, 1.95, 'beat', framerate=50)
    timer.wait(2, 'beat')

def dafist_clignotageA(seq, timer):
    # seq.send('/BC/White/All', 0)
    seq.send('/CC/Red/Segment/8', 0)
    seq.send('/CC/Green/Segment/8', 0)
    seq.send('/CJ/Red/Segment/1', 0)
    seq.send('/CJ/Green/Segment/1', 0)
    seq.send('/CC/Red/Segment/7', 0)
    seq.send('/CC/Green/Segment/7', 0)
    seq.send('/CJ/Red/Segment/2', 0)
    seq.send('/CJ/Green/Segment/2', 0)


    seq.send('/BC/Red/Segment/1', 255)
    seq.send('/BC/Green/Segment/1', 70)
    seq.send('/BC/Red/Segment/2', 255)
    seq.send('/BC/Green/Segment/2', 70)
    seq.send('/BC/Red/Segment/3', 255)
    seq.send('/BC/Green/Segment/3', 70)
    seq.send('/BC/Red/Segment/4', 255)
    seq.send('/BC/Green/Segment/4', 70)
    seq.send('/BC/Red/Segment/5', 0)
    seq.send('/BC/Green/Segment/5', 0)
    seq.send('/BC/Red/Segment/6', 0)
    seq.send('/BC/Green/Segment/6', 0)
    seq.send('/BC/Red/Segment/7', 0)
    seq.send('/BC/Green/Segment/7', 0)
    seq.send('/BC/Red/Segment/8', 0)
    seq.send('/BC/Green/Segment/8', 0)

    seq.send('/BJ/Red/Segment/5', 255)
    seq.send('/BJ/Green/Segment/5', 70)
    seq.send('/BJ/Red/Segment/6', 255)
    seq.send('/BJ/Green/Segment/6', 70)
    seq.send('/BJ/Red/Segment/7', 255)
    seq.send('/BJ/Green/Segment/7', 70)
    seq.send('/BJ/Red/Segment/8', 255)
    seq.send('/BJ/Green/Segment/8', 70)
    seq.send('/BJ/Red/Segment/1', 0)
    seq.send('/BJ/Green/Segment/1', 0)
    seq.send('/BJ/Red/Segment/2', 0)
    seq.send('/BJ/Green/Segment/2', 0)
    seq.send('/BJ/Red/Segment/3', 0)
    seq.send('/BJ/Green/Segment/3', 0)
    seq.send('/BJ/Red/Segment/4', 0)
    seq.send('/BJ/Green/Segment/4', 0)


def dafist_clignotageB(seq, timer):
    # seq.send('/BC/White/All', 0)
    seq.send('/CC/Red/Segment/8', 255)
    seq.send('/CC/Green/Segment/8', 70)
    seq.send('/CJ/Red/Segment/1', 255)
    seq.send('/CJ/Green/Segment/1', 70)
    seq.send('/CC/Red/Segment/7', 255)
    seq.send('/CC/Green/Segment/7', 70)
    seq.send('/CJ/Red/Segment/2', 255)
    seq.send('/CJ/Green/Segment/2', 70)


    seq.send('/BC/Red/Segment/5', 255)
    seq.send('/BC/Green/Segment/5', 70)
    seq.send('/BC/Red/Segment/6', 255)
    seq.send('/BC/Green/Segment/6', 70)
    seq.send('/BC/Red/Segment/7', 255)
    seq.send('/BC/Green/Segment/7', 70)
    seq.send('/BC/Red/Segment/8', 255)
    seq.send('/BC/Green/Segment/8', 70)
    seq.send('/BC/Red/Segment/1', 0)
    seq.send('/BC/Green/Segment/1', 0)
    seq.send('/BC/Red/Segment/2', 0)
    seq.send('/BC/Green/Segment/2', 0)
    seq.send('/BC/Red/Segment/3', 0)
    seq.send('/BC/Green/Segment/3', 0)
    seq.send('/BC/Red/Segment/4', 0)
    seq.send('/BC/Green/Segment/4', 0)

    seq.send('/BJ/Red/Segment/1', 255)
    seq.send('/BJ/Green/Segment/1', 70)
    seq.send('/BJ/Red/Segment/2', 255)
    seq.send('/BJ/Green/Segment/2', 70)
    seq.send('/BJ/Red/Segment/3', 255)
    seq.send('/BJ/Green/Segment/3', 70)
    seq.send('/BJ/Red/Segment/4', 255)
    seq.send('/BJ/Green/Segment/4', 70)
    seq.send('/BJ/Red/Segment/5', 0)
    seq.send('/BJ/Green/Segment/5', 0)
    seq.send('/BJ/Red/Segment/6', 0)
    seq.send('/BJ/Green/Segment/6', 0)
    seq.send('/BJ/Red/Segment/7', 0)
    seq.send('/BJ/Green/Segment/7', 0)
    seq.send('/BJ/Red/Segment/8', 0)
    seq.send('/BJ/Green/Segment/8', 0)

def dafist_blinderstrob(seq, timer):
    for i in range(1,6):
        seq.send('/BJ/White/Segment/All', 255)
        timer.wait(0.05, 's')
        seq.send('/BJ/White/Segment/All', 0)
        timer.wait(0.05, 's')

def dafist_roulettearabesques(seq, timer):
    seq.send(vporlport, '/pyta/slide/visible', 60, 1)
    seq.send(vporlport, '/pyta/slide/visible', 63, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 61, 1)
    seq.send(vporlport, '/pyta/slide/visible', 60, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 62, 1)
    seq.send(vporlport, '/pyta/slide/visible', 61, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 63, 1)
    seq.send(vporlport, '/pyta/slide/visible', 62, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 60, 1)
    seq.send(vporlport, '/pyta/slide/visible', 63, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 61, 1)
    seq.send(vporlport, '/pyta/slide/visible', 60, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 62, 1)
    seq.send(vporlport, '/pyta/slide/visible', 61, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 63, 1)
    seq.send(vporlport, '/pyta/slide/visible', 62, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 60, 1)
    seq.send(vporlport, '/pyta/slide/visible', 63, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 61, 1)
    seq.send(vporlport, '/pyta/slide/visible', 60, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 62, 1)
    seq.send(vporlport, '/pyta/slide/visible', 61, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 63, 1)
    seq.send(vporlport, '/pyta/slide/visible', 62, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 60, 1)
    seq.send(vporlport, '/pyta/slide/visible', 63, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 61, 1)
    seq.send(vporlport, '/pyta/slide/visible', 60, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 62, 1)
    seq.send(vporlport, '/pyta/slide/visible', 61, 0)
    timer.wait(.125,'b')
    seq.send(vporlport, '/pyta/slide/visible', 63, 1)
    seq.send(vporlport, '/pyta/slide/visible', 62, 0)
    timer.wait(.125,'b')

def dafist_patatetemps(seq, timer):
    seq.send(':/Lightseq/Scene/Stop', 'dafist_roulettearabesques')
    seq.send(':/Lightseq/Sequence/Disable', 'dafist_roulettearabesques')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 1, 1, 1)
    timer.wait(0.5, 'bite')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 0, 0, 0)
    seq.scene_play('dafist_roulettearabesques')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 1, 0.3, 0)
    seq.send(':/Lightseq/Sequence/Enable', 'dafist_roulettearabesques')


def dafist_patatesyncope(seq, timer):
    timer.wait(0.75, 'bite')
    seq.send(':/Lightseq/Scene/Stop', 'dafist_roulettearabesques')
    seq.send(':/Lightseq/Sequence/Disable', 'dafist_roulettearabesques')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 1, 1, 1)
    timer.wait(0.25, 'bite')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 0, 0, 0)
    timer.wait(0.25, 'bite')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 1, 1, 1)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 1, 1, 1)
    timer.wait(0.25, 'bite')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 0, 0, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 0, 0, 0)
    timer.wait(0.25, 'bite')
    seq.send(vporlport, '/pyta/slide/rgb', 63, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 62, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 61, 1, 0.3, 0)
    seq.send(vporlport, '/pyta/slide/rgb', 60, 1, 0.3, 0)
    seq.send(':/Lightseq/Scene/Play', 'dafist_roulettearabesques')
    seq.send(':/Lightseq/Sequence/Enable', 'dafist_roulettearabesques')

def dafist_vpoff(seq, timer):
    seq.send(vporlport, '/pyta/slide/visible', -1, 0)
