[
    {
        "id": "",
        "label": "Plagiat Lights",
        "widgets": [
            {
                "type": "strip",
                "top": 380,
                "left": 740,
                "id": "BC",
                "label": "auto",
                "width": 570,
                "height": 70,
                "color": "rgb(0,0,0)",
                "widgets": [
                    {
                        "type": "rgbled",
                        "id": "BC_1",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_1",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_2",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_2",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_3",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_3",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_4",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_4",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_5",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_5",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_6",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_6",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_7",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_7",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BC_8",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BC_8",
                        "preArgs": []
                    }
                ],
                "horizontal": true,
                "css": ""
            },
            {
                "type": "strip",
                "top": 380,
                "left": 150,
                "id": "BJ",
                "label": "auto",
                "width": 570,
                "height": 70,
                "color": "rgb(0,0,0)",
                "css": "& {flex-direction:row-reverse}",
                "widgets": [
                    {
                        "type": "rgbled",
                        "id": "BJ_1",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_1",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_2",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_2",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_3",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_3",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_4",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_4",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_5",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_5",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_6",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_6",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_7",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_7",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "BJ_8",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/BJ_8",
                        "preArgs": []
                    }
                ],
                "horizontal": true
            },
            {
                "type": "strip",
                "top": 500,
                "left": 740,
                "id": "CC",
                "label": "auto",
                "width": 130,
                "height": 270,
                "color": "rgb(0,0,0)",
                "css": ".widget {height:12.5%}",
                "widgets": [
                    {
                        "type": "rgbled",
                        "id": "CC_1",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_1",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_2",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_2",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_3",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_3",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_4",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_4",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_5",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_5",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_6",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_6",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_7",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_7",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CC_8",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CC_8",
                        "preArgs": []
                    }
                ],
                "horizontal": false
            },
            {
                "type": "strip",
                "top": 500,
                "left": 580,
                "id": "CJ",
                "label": "auto",
                "width": 140,
                "height": 270,
                "color": "rgb(0,0,0)",
                "widgets": [
                    {
                        "type": "rgbled",
                        "id": "CJ_1",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_1",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_2",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_2",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_3",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_3",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_4",
                        "label": false,
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_4",
                        "width": "auto",
                        "height": "auto",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_5",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_5",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_6",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_6",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_7",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_7",
                        "preArgs": []
                    },
                    {
                        "type": "rgbled",
                        "id": "CJ_8",
                        "label": false,
                        "width": "auto",
                        "height": "auto",
                        "css": "",
                        "widgetId": "",
                        "value": 1,
                        "address": "/CJ_8",
                        "preArgs": []
                    }
                ],
                "horizontal": false,
                "css": ".widget {height:12.5%}; .strip {flex-direction:column-reverse}"
            }
        ]
    }
]